### ISSUE TITLE
Build fails (UnusedBytecodeStripper2 error)

### ISSUE THREAD

**Issue by PgnDvd** [brnkhy/MapzenGo#39]
When trying to build inserting only the CachedDynamicLoader as a scene I get the following error and no build files are generated. I think is because some paths with mixed separators (I'm on Windows) like this:
"C:\Tactics\OpenMap3/Temp/StagingArea/Data/methods_pointedto_by_uievents.xml" 

Can you point me at the settings files where these paths are set?

Here is the message extracted from the log

```
Invoking UnusedByteCodeStripper2 with arguments: -out "C:\Tactics\OpenMap3\Temp\StagingArea\Data\Managed\tempStrip" -l none -c link -b False -x "C:\Program Files\Unity\Editor\Data\PlaybackEngines\WebGLSupport\Whitelists\Core.xml" -f "C:\Program Files\Unity\Editor\Data\il2cpp\LinkerDescriptors" -x "C:\Tactics\OpenMap3/Temp/StagingArea/Data/methods_pointedto_by_uievents.xml" -x "C:\Tactics\OpenMap3\Temp\StagingArea\Data\preserved_derived_types.xml" -d "C:\Tactics\OpenMap3\Temp\StagingArea\Data\Managed" -a  "C:\Tactics\OpenMap3\Temp\StagingArea\Data\Managed\Assembly-CSharp.dll" -a  "C:\Tactics\OpenMap3\Temp\StagingArea\Data\Managed\Assembly-UnityScript.dll" -a  "C:\Tactics\OpenMap3\Temp\StagingArea\Data\Managed\UnityEngine.Analytics.dll"
C:\Program Files\Unity\Editor\Data\Tools/UnusedByteCodeStripper2/UnusedBytecodeStripper2.exe exited after 698 ms.
Failed running C:\Program Files\Unity\Editor\Data\Tools/UnusedByteCodeStripper2/UnusedBytecodeStripper2.exe -out "C:\Tactics\OpenMap3\Temp\StagingArea\Data\Managed\tempStrip" -l none -c link -b False -x "C:\Program Files\Unity\Editor\Data\PlaybackEngines\WebGLSupport\Whitelists\Core.xml" -f "C:\Program Files\Unity\Editor\Data\il2cpp\LinkerDescriptors" -x "C:\Tactics\OpenMap3/Temp/StagingArea/Data/methods_pointedto_by_uievents.xml" -x "C:\Tactics\OpenMap3\Temp\StagingArea\Data\preserved_derived_types.xml" -d "C:\Tactics\OpenMap3\Temp\StagingArea\Data\Managed" -a  "C:\Tactics\OpenMap3\Temp\StagingArea\Data\Managed\Assembly-CSharp.dll" -a  "C:\Tactics\OpenMap3\Temp\StagingArea\Data\Managed\Assembly-UnityScript.dll" -a  "C:\Tactics\OpenMap3\Temp\StagingArea\Data\Managed\UnityEngine.Analytics.dll"

stdout:
ERROR: Failed to resolve base type System.Configuration.ApplicationSettingsBase for type SSAA.Properties.Settings
Fatal error in Mono CIL Linker
System.Exception: ERROR: Failed to resolve base type System.Configuration.ApplicationSettingsBase for type SSAA.Properties.Settings
   at UnusedBytecodeStripper2.ResolveFromMonoBehaviours.IsMonoBehaviourOrScriptableObject(TypeDefinition type)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at UnusedBytecodeStripper2.ResolveFromMonoBehaviours.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at Mono.Linker.Driver.RunDriver(Driver driver)
stderr:

UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
UnityEditorInternal.Runner:RunManagedProgram(String, String, String, CompilerOutputParserBase, Action`1) (at C:\buildslave\unity\build\Editor\Mono\BuildPipeline\Il2Cpp\IL2CPPUtils.cs:98)
UnityEditorInternal.AssemblyStripper:RunAssemblyLinker(IEnumerable`1, String&, String&, String, String) (at C:\buildslave\unity\build\Editor\Mono\BuildPipeline\AssemblyStripper.cs:104)
UnityEditorInternal.AssemblyStripper:StripAssembliesTo(String[], String[], String, String, String&, String&, String, IIl2CppPlatformProvider, IEnumerable`1, Boolean) (at C:\buildslave\unity\build\Editor\Mono\BuildPipeline\AssemblyStripper.cs:97)
UnityEditorInternal.AssemblyStripper:RunAssemblyStripper(String, IEnumerable, String, String[], String[], String, IIl2CppPlatformProvider, RuntimeClassRegistry, Boolean) (at C:\buildslave\unity\build\Editor\Mono\BuildPipeline\AssemblyStripper.cs:208)
UnityEditorInternal.AssemblyStripper:StripAssemblies(String, IIl2CppPlatformProvider, RuntimeClassRegistry, Boolean) (at C:\buildslave\unity\build\Editor\Mono\BuildPipeline\AssemblyStripper.cs:128)
UnityEditorInternal.IL2CPPBuilder:Run() (at C:\buildslave\unity\build\Editor\Mono\BuildPipeline\Il2Cpp\IL2CPPUtils.cs:205)
UnityEditorInternal.IL2CPPUtils:RunIl2Cpp(String, IIl2CppPlatformProvider, Action`1, RuntimeClassRegistry, Boolean) (at C:\buildslave\unity\build\Editor\Mono\BuildPipeline\Il2Cpp\IL2CPPUtils.cs:139)
UnityEditor.WebGL.WebGlBuildPostprocessor:PostProcess(BuildPostProcessArgs) (at /Users/builduser/buildslave/unity/build/PlatformDependent/WebGL/Extensions/Unity.WebGL.extensions/BuildPostprocessor.cs:373)
UnityEditor.PostprocessBuildPlayer:Postprocess(BuildTarget, String, String, String, Int32, Int32, String, String, BuildOptions, RuntimeClassRegistry, BuildReport) (at C:\buildslave\unity\build\Editor\Mono\BuildPipeline\PostprocessBuildPlayer.cs:176)

(Filename: /Users/builduser/buildslave/unity/build/PlatformDependent/WebGL/Extensions/Unity.WebGL.extensions/BuildPostprocessor.cs Line: 373)

Exception: C:\Program Files\Unity\Editor\Data\Tools/UnusedByteCodeStripper2/UnusedBytecodeStripper2.exe did not run properly!
  at UnityEditorInternal.Runner.RunManagedProgram (System.String exe, System.String args, System.String workingDirectory, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser, System.Action`1 setupStartInfo) [0x00160] in C:\buildslave\unity\build\Editor\Mono\BuildPipeline\Il2Cpp\IL2CPPUtils.cs:100 
  at UnityEditorInternal.AssemblyStripper.RunAssemblyLinker (IEnumerable`1 args, System.String& out, System.String& err, System.String linkerPath, System.String workingDirectory) [0x00034] in C:\buildslave\unity\build\Editor\Mono\BuildPipeline\AssemblyStripper.cs:104 
  at UnityEditorInternal.AssemblyStripper.StripAssembliesTo (System.String[] assemblies, System.String[] searchDirs, System.String outputFolder, System.String workingDirectory, System.String& output, System.String& error, System.String linkerPath, IIl2CppPlatformProvider platformProvider, IEnumerable`1 additionalBlacklist, Boolean developmentBuild) [0x001b1] in C:\buildslave\unity\build\Editor\Mono\BuildPipeline\AssemblyStripper.cs:97 
  at UnityEditorInternal.AssemblyStripper.RunAssemblyStripper (System.String stagingAreaData, IEnumerable assemblies, System.String managedAssemblyFolderPath, System.String[] assembliesToStrip, System.String[] searchDirs, System.String monoLinkerPath, IIl2CppPlatformProvider platformProvider, UnityEditor.RuntimeClassRegistry rcr, Boolean developmentBuild) [0x000cc] in C:\buildslave\unity\build\Editor\Mono\BuildPipeline\AssemblyStripper.cs:208 
  at UnityEditorInternal.AssemblyStripper.StripAssemblies (System.String stagingAreaData, IIl2CppPlatformProvider platformProvider, UnityEditor.RuntimeClassRegistry rcr, Boolean developmentBuild) [0x0002b] in C:\buildslave\unity\build\Editor\Mono\BuildPipeline\AssemblyStripper.cs:128 
  at UnityEditorInternal.IL2CPPBuilder.Run () [0x00051] in C:\buildslave\unity\build\Editor\Mono\BuildPipeline\Il2Cpp\IL2CPPUtils.cs:205 
  at UnityEditorInternal.IL2CPPUtils.RunIl2Cpp (System.String stagingAreaData, IIl2CppPlatformProvider platformProvider, System.Action`1 modifyOutputBeforeCompile, UnityEditor.RuntimeClassRegistry runtimeClassRegistry, Boolean developmentBuild) [0x0000d] in C:\buildslave\unity\build\Editor\Mono\BuildPipeline\Il2Cpp\IL2CPPUtils.cs:139 
  at UnityEditor.WebGL.WebGlBuildPostprocessor.PostProcess (BuildPostProcessArgs args) [0x001ee] in /Users/builduser/buildslave/unity/build/PlatformDependent/WebGL/Extensions/Unity.WebGL.extensions/BuildPostprocessor.cs:373 
  at UnityEditor.PostprocessBuildPlayer.Postprocess (BuildTarget target, System.String installPath, System.String companyName, System.String productName, Int32 width, Int32 height, System.String downloadWebplayerUrl, System.String manualDownloadWebplayerUrl, BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.BuildReporting.BuildReport report) [0x000ce] in C:\buildslave\unity\build\Editor\Mono\BuildPipeline\PostprocessBuildPlayer.cs:176 

(Filename: /Users/builduser/buildslave/unity/build/PlatformDependent/WebGL/Extensions/Unity.WebGL.extensions/BuildPostprocessor.cs Line: 373)

```

**Comment by brnkhy** [comment]
are you trying a webgl build? I honestly doubt that'll work.
Other than that, it looks like an internal error and those paths are not even mine.  It says somethings about SSAA there so I might forgot some SSAA asset files, you can check and delete them as well. (check camera for missing scripts)
That's all I can think of.

**Comment by PgnDvd** [comment]
Yes, I was trying to build for webgl (sorry, I'm quite new to Unity). Which platform you usually target when building? Do you think it will ever support webgl build?

**Comment by brnkhy** [comment]
I'm currently working on desktop, will probably move to mobile after fixing some issues.  I really don't want to work with web builds as they are generally problematic, not popular or useful.
If you're aiming for web builds though, I would highly suggest stripping it down and using a very simplified version of it. I doubt it can handle all of it (and there are much more coming).
